### ISSUE TITLE
Epic: reducing data overfetch to allow for progressive loading

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#283]
We'll explicitly program filters that correspond to those on the frontend instead of trying for a generic solution due to the complex nature of the problem. The only parameters that should be generic are the `page`, `limit`, and ordering parameters.

- [x] /api/participants
  - [x] `participant_codename`, `notes`: LIKE
  - [x] `participant_type`, `sex`: IN list
  - [x] `affected`, `solved`: exact match (== true/false/null)
  - [x] `family_codename` LIKE (needs join)
  - [x] ~~`dataset_type`: IN list (needs join)~~ cancelled
- [x] /api/datasets
  - [x] `family_codename`, `participant_codename`, `updated_by`: LIKE (needs join)
  - [x] `tissue_sample_type`: IN list (needs join)
  - [x] `dataset_type`, `condition`: IN list
  - [x] `notes`: LIKE
  - [x] `files`: LIKE (needs join or querying on a different table); querying by the number of files is optional
  - [x] `updated`: date range (leq/geq)
- [x] /api/analyses
  - [x] `assignee`, `requester`: LIKE (needs join)
  - [x] `updated`: date range (leq/geq)
  - [x] `path_prefix` ,`notes`: LIKE
  - [x] `status`: IN list
  - [x] ~`pipeline`: skip~ 

## Original
**Overfetch: add limit, order, query parameters to all list endpoints**

We want to add parameters that correspond to LIMIT BY (reducing rows returned) and ORDER BY (so the order is predictable), along with a parameter that specifies the index (which page to return) to reduce slow loading as a result of massive overfetch.

We want to add query parameters that correspond to WHERE clauses with LIKE conditions so that the frontend filters can be hooked into these under progressive loading. Thus we need to specify what column we are querying on and what value specifically, exact match, or range.

Optionally, we can add a parameter that specifies exactly which columns to return in this request to further reduce overfetch.
