### ISSUE TITLE
The big DevOps to-do list for production

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#315]
- [x] Automatically deploy frontend to MinIO from GitHub Actions
- [x] Automatically deploy backend container to GitHub Container Registry on the ccmbioinfo organization. Exclude tests from this production image.
- [x] Add Watchtower to Compose deployments after we deploy to a registry and reset the dev VM
- [x] Use journald in production
- [x] Configure Dependabot for automatic dependency upgrades (not just security): JavaScript, Python, Docker, Actions
- [x] Add CodeQL static analyzer on Actions
