### ISSUE TITLE
Epic: database migration from old Sample Tracker

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#33]
Take the opportunity to clean out garbage data and clerical errors

- [x] user (figure out deactivation)
- [x] analysis
- [x] dataset
- [x] tissue sample
- [x] participant
- [x] family
- [x] group
- [ ] analysis_datasets

**Comment by helrick** [comment]
updates in ccmbioinfo/ST2020db/pull/3 which includes preliminary mapping of datasets and tissue_sample tables

**Comment by kevinlul** [comment]
Things that will affect the main migration:
- [ ] #244 user foreign key column renames
- [ ] #230 file path field restructuring
- [ ] #207 new columns

Usable with instructions in [ccmbioinfo/ST2020db](https://github.com/ccmbioinfo/ST2020db). Can optionally add a submodule to this repository.

**Comment by kevinlul** [comment]
Closing as this has not been that useful for tracking progress
