### ISSUE TITLE
Epic: priority flags for analyses

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#505]
Currently, the workflow for infrequent high-priority analyses involves a chain of emails. As a collaborator requesting analyses, I want to label requested analyses as "clinical priority" or "research priority" if needed to streamline this process.

Tasks:
- [x] Database: add a nullable enum column to the analysis table for priority. This can go in the "initial migration" if done before Stager rollout, and definitely before the variant viewer migration if possible.
- [ ] Backend: support this feature in all analysis endpoints once the database change is made
- [ ] Frontend: add a radio button to the analysis request modal to apply a priority flag if desired (clinical, research, none)
- [ ] Frontend: highlight analyses in the main table to distinguish their priority. Add filters or chip buttons for priority. Maybe sort priority analyses to appear first if they are not completed yet.
