### ISSUE TITLE
Variant export enhancements

### ISSUE THREAD

**Issue by cklamann** [ccmbioinfo/stager#655]
- [x] include as many columns for the report in the export as possible (#691)
- [x] allow users to search by region/variant position/rsId (#717)
- [x] allow users to select fields they want included in report  (#687)
