### ISSUE TITLE
Epic: CCM deployment

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/stager#909]
- [x] #908
- [x] Flask: add MINIO_TLS boolean environment variable to configure `secure` flag to MinioAdmin and MinioClient; we likely won't have unencrypted access to the lab-specific tenants #954 
- [x] Provision a production host in HSC_Hosted on CCM hardware, routing stager.ccm.sickkids.ca and stager-LAB.ccm.sickkids.ca
- [x] Provision a MySQL database server in HSC_Hosted on CCM hardware, accessible only through the Stager VM
- [x] Provision a self-hosted Actions runner in HSC_CCM for deploying to CCM production
- [x] Deploy MySQL server and migrate data from stager-dev
- [x] Add stacks and workflows to deploy the backends in corresponding environments

from #875

**Comment by kevinlul** [comment]
Prod VMs creted as described.

**Comment by kevinlul** [comment]
Actions runner available with label `ccm`

**Comment by kevinlul** [comment]
Notes: `automysqlbackup` has been a Debian package since 9 Stretch and an Ubuntu package since 18.04 Bionic. Worth trying instead of reinventing the wheel, and maybe a baremetal installation is worth it to be more conventional.

**Comment by kevinlul** [comment]
MySQL ready
